# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mohamad/Desktop/C++/Ezu-Hub

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mohamad/Desktop/C++/Ezu-Hub

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mohamad/Desktop/C++/Ezu-Hub/CMakeFiles /home/mohamad/Desktop/C++/Ezu-Hub//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mohamad/Desktop/C++/Ezu-Hub/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Ezu-Hub

# Build rule for target.
Ezu-Hub: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Ezu-Hub
.PHONY : Ezu-Hub

# fast build rule for target.
Ezu-Hub/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ezu-Hub.dir/build.make CMakeFiles/Ezu-Hub.dir/build
.PHONY : Ezu-Hub/fast

#=============================================================================
# Target rules for targets named Ezu-Hub_autogen_timestamp_deps

# Build rule for target.
Ezu-Hub_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Ezu-Hub_autogen_timestamp_deps
.PHONY : Ezu-Hub_autogen_timestamp_deps

# fast build rule for target.
Ezu-Hub_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ezu-Hub_autogen_timestamp_deps.dir/build.make CMakeFiles/Ezu-Hub_autogen_timestamp_deps.dir/build
.PHONY : Ezu-Hub_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named Ezu-Hub_autogen

# Build rule for target.
Ezu-Hub_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Ezu-Hub_autogen
.PHONY : Ezu-Hub_autogen

# fast build rule for target.
Ezu-Hub_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ezu-Hub_autogen.dir/build.make CMakeFiles/Ezu-Hub_autogen.dir/build
.PHONY : Ezu-Hub_autogen/fast

checkwindow.o: checkwindow.cpp.o
.PHONY : checkwindow.o

# target to build an object file
checkwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ezu-Hub.dir/build.make CMakeFiles/Ezu-Hub.dir/checkwindow.cpp.o
.PHONY : checkwindow.cpp.o

checkwindow.i: checkwindow.cpp.i
.PHONY : checkwindow.i

# target to preprocess a source file
checkwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ezu-Hub.dir/build.make CMakeFiles/Ezu-Hub.dir/checkwindow.cpp.i
.PHONY : checkwindow.cpp.i

checkwindow.s: checkwindow.cpp.s
.PHONY : checkwindow.s

# target to generate assembly for a file
checkwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ezu-Hub.dir/build.make CMakeFiles/Ezu-Hub.dir/checkwindow.cpp.s
.PHONY : checkwindow.cpp.s

creet.o: creet.cpp.o
.PHONY : creet.o

# target to build an object file
creet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ezu-Hub.dir/build.make CMakeFiles/Ezu-Hub.dir/creet.cpp.o
.PHONY : creet.cpp.o

creet.i: creet.cpp.i
.PHONY : creet.i

# target to preprocess a source file
creet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ezu-Hub.dir/build.make CMakeFiles/Ezu-Hub.dir/creet.cpp.i
.PHONY : creet.cpp.i

creet.s: creet.cpp.s
.PHONY : creet.s

# target to generate assembly for a file
creet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ezu-Hub.dir/build.make CMakeFiles/Ezu-Hub.dir/creet.cpp.s
.PHONY : creet.cpp.s

firswindow.o: firswindow.cpp.o
.PHONY : firswindow.o

# target to build an object file
firswindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ezu-Hub.dir/build.make CMakeFiles/Ezu-Hub.dir/firswindow.cpp.o
.PHONY : firswindow.cpp.o

firswindow.i: firswindow.cpp.i
.PHONY : firswindow.i

# target to preprocess a source file
firswindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ezu-Hub.dir/build.make CMakeFiles/Ezu-Hub.dir/firswindow.cpp.i
.PHONY : firswindow.cpp.i

firswindow.s: firswindow.cpp.s
.PHONY : firswindow.s

# target to generate assembly for a file
firswindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ezu-Hub.dir/build.make CMakeFiles/Ezu-Hub.dir/firswindow.cpp.s
.PHONY : firswindow.cpp.s

lhome.o: lhome.cpp.o
.PHONY : lhome.o

# target to build an object file
lhome.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ezu-Hub.dir/build.make CMakeFiles/Ezu-Hub.dir/lhome.cpp.o
.PHONY : lhome.cpp.o

lhome.i: lhome.cpp.i
.PHONY : lhome.i

# target to preprocess a source file
lhome.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ezu-Hub.dir/build.make CMakeFiles/Ezu-Hub.dir/lhome.cpp.i
.PHONY : lhome.cpp.i

lhome.s: lhome.cpp.s
.PHONY : lhome.s

# target to generate assembly for a file
lhome.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ezu-Hub.dir/build.make CMakeFiles/Ezu-Hub.dir/lhome.cpp.s
.PHONY : lhome.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ezu-Hub.dir/build.make CMakeFiles/Ezu-Hub.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ezu-Hub.dir/build.make CMakeFiles/Ezu-Hub.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ezu-Hub.dir/build.make CMakeFiles/Ezu-Hub.dir/main.cpp.s
.PHONY : main.cpp.s

Ezu-Hub_autogen/EWIEGA46WW/qrc_qrc.o: Ezu-Hub_autogen/EWIEGA46WW/qrc_qrc.cpp.o
.PHONY : Ezu-Hub_autogen/EWIEGA46WW/qrc_qrc.o

# target to build an object file
Ezu-Hub_autogen/EWIEGA46WW/qrc_qrc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ezu-Hub.dir/build.make CMakeFiles/Ezu-Hub.dir/Ezu-Hub_autogen/EWIEGA46WW/qrc_qrc.cpp.o
.PHONY : Ezu-Hub_autogen/EWIEGA46WW/qrc_qrc.cpp.o

Ezu-Hub_autogen/EWIEGA46WW/qrc_qrc.i: Ezu-Hub_autogen/EWIEGA46WW/qrc_qrc.cpp.i
.PHONY : Ezu-Hub_autogen/EWIEGA46WW/qrc_qrc.i

# target to preprocess a source file
Ezu-Hub_autogen/EWIEGA46WW/qrc_qrc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ezu-Hub.dir/build.make CMakeFiles/Ezu-Hub.dir/Ezu-Hub_autogen/EWIEGA46WW/qrc_qrc.cpp.i
.PHONY : Ezu-Hub_autogen/EWIEGA46WW/qrc_qrc.cpp.i

Ezu-Hub_autogen/EWIEGA46WW/qrc_qrc.s: Ezu-Hub_autogen/EWIEGA46WW/qrc_qrc.cpp.s
.PHONY : Ezu-Hub_autogen/EWIEGA46WW/qrc_qrc.s

# target to generate assembly for a file
Ezu-Hub_autogen/EWIEGA46WW/qrc_qrc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ezu-Hub.dir/build.make CMakeFiles/Ezu-Hub.dir/Ezu-Hub_autogen/EWIEGA46WW/qrc_qrc.cpp.s
.PHONY : Ezu-Hub_autogen/EWIEGA46WW/qrc_qrc.cpp.s

Ezu-Hub_autogen/mocs_compilation.o: Ezu-Hub_autogen/mocs_compilation.cpp.o
.PHONY : Ezu-Hub_autogen/mocs_compilation.o

# target to build an object file
Ezu-Hub_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ezu-Hub.dir/build.make CMakeFiles/Ezu-Hub.dir/Ezu-Hub_autogen/mocs_compilation.cpp.o
.PHONY : Ezu-Hub_autogen/mocs_compilation.cpp.o

Ezu-Hub_autogen/mocs_compilation.i: Ezu-Hub_autogen/mocs_compilation.cpp.i
.PHONY : Ezu-Hub_autogen/mocs_compilation.i

# target to preprocess a source file
Ezu-Hub_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ezu-Hub.dir/build.make CMakeFiles/Ezu-Hub.dir/Ezu-Hub_autogen/mocs_compilation.cpp.i
.PHONY : Ezu-Hub_autogen/mocs_compilation.cpp.i

Ezu-Hub_autogen/mocs_compilation.s: Ezu-Hub_autogen/mocs_compilation.cpp.s
.PHONY : Ezu-Hub_autogen/mocs_compilation.s

# target to generate assembly for a file
Ezu-Hub_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ezu-Hub.dir/build.make CMakeFiles/Ezu-Hub.dir/Ezu-Hub_autogen/mocs_compilation.cpp.s
.PHONY : Ezu-Hub_autogen/mocs_compilation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Ezu-Hub_autogen"
	@echo "... Ezu-Hub_autogen_timestamp_deps"
	@echo "... Ezu-Hub"
	@echo "... checkwindow.o"
	@echo "... checkwindow.i"
	@echo "... checkwindow.s"
	@echo "... creet.o"
	@echo "... creet.i"
	@echo "... creet.s"
	@echo "... firswindow.o"
	@echo "... firswindow.i"
	@echo "... firswindow.s"
	@echo "... lhome.o"
	@echo "... lhome.i"
	@echo "... lhome.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... Ezu-Hub_autogen/EWIEGA46WW/qrc_qrc.o"
	@echo "... Ezu-Hub_autogen/EWIEGA46WW/qrc_qrc.i"
	@echo "... Ezu-Hub_autogen/EWIEGA46WW/qrc_qrc.s"
	@echo "... Ezu-Hub_autogen/mocs_compilation.o"
	@echo "... Ezu-Hub_autogen/mocs_compilation.i"
	@echo "... Ezu-Hub_autogen/mocs_compilation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

